version: "3"
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "9090:8080"
    volumes:
      - /mnt/TANK/docker/ai/openwebui/data:/app/backend/data
  mcpo-proxy:
    image: ghcr.io/model-context-protocol/mcpo:latest
    ports:
      - "8000:8000"
    command: --tcp-downstream 192.168.86.3:8999
    restart: unless-stopped  
